server:
  port: 8671
spring:
  profiles: instance1
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    preferIpAddress: false
    hostname: peer1
    metadataMap:
      zone: zone1
  client:
    serviceUrl:
      defaultZone: http://admin:admin@peer2:8672/eureka/,http://admin:admin@peer3:8673/eureka/
    registerWithEureka: false
    fetchRegistry: false
    #https://www.baeldung.com/spring-cloud-netflix-eureka#transportexception-cannot-execute-request-on-any-known-server
    registryFetchIntervalMs: 3000
