server:
  port: 8673
spring:
  profiles: instance3
  application:
    name: eureka-server
  security:
    user:
      name: admin
      password: admin
eureka:
  instance:
    preferIpAddress: false
    hostname: peer3
    metadataMap:
      zone: zone3
  client:
    service-url:
      defaultZone: http://admin:admin@peer1:8671/eureka/,http://admin:admin@peer2:8672/eureka/
    registerWithEureka: false
    fetchRegistry: false
    #https://www.baeldung.com/spring-cloud-netflix-eureka#transportexception-cannot-execute-request-on-any-known-server
    registryFetchIntervalMs: 3000
